export const PLURID_DEFAULT_CONFIGURATION_SPACE_CULLING_DISTANCE = 1_500;


export const PLURID_DEFAULT_CONFIGURATION_LINK_SUFFIX = "'";

export const PLURID_DEFAULT_CONFIGURATION_LINK_PREVIEW_SHOW = true;
export const PLURID_DEFAULT_CONFIGURATION_LINK_PREVIEW_FADE_IN = 400;
export const PLURID_DEFAULT_CONFIGURATION_LINK_PREVIEW_FADE_OUT = 400;
export const PLURID_DEFAULT_CONFIGURATION_LINK_PREVIEW_OFFSET_X = 5;
export const PLURID_DEFAULT_CONFIGURATION_LINK_PREVIEW_OFFSET_Y = 0;
