export enum SHORTCUTS {
    ROTATE_UP = 'ROTATE_UP',
    ROTATE_DOWN = 'ROTATE_DOWN',
    ROTATE_LEFT = 'ROTATE_LEFT',
    ROTATE_RIGHT = 'ROTATE_RIGHT',
    TRANSLATE_UP = 'TRANSLATE_UP',
    TRANSLATE_DOWN = 'TRANSLATE_DOWN',
    TRANSLATE_LEFT = 'TRANSLATE_LEFT',
    TRANSLATE_RIGHT = 'TRANSLATE_RIGHT',
    SCALE_UP = 'SCALE_UP',
    SCALE_DOWN = 'SCALE_DOWN',
}
