export enum SHORTCUTS {
    TOGGLE_FIRST_PERSON = 'TOGGLE_FIRST_PERSON',
    MOVE_FORWARD = 'MOVE_FORWARD',
    MOVE_BACKWARD = 'MOVE_BACKWARD',
    MOVE_LEFT = 'MOVE_LEFT',
    MOVE_RIGHT = 'MOVE_RIGHT',
    MOVE_UP = 'MOVE_UP',
    MOVE_DOWN = 'MOVE_DOWN',
    TURN_LEFT = 'TURN_LEFT',
    TURN_RIGHT = 'TURN_RIGHT',
    TURN_UP = 'TURN_UP',
    TURN_DOWN = 'TURN_DOWN',

    ROTATE_UP = 'ROTATE_UP',
    ROTATE_DOWN = 'ROTATE_DOWN',
    ROTATE_LEFT = 'ROTATE_LEFT',
    ROTATE_RIGHT = 'ROTATE_RIGHT',
    TOGGLE_ROTATE = 'TOGGLE_ROTATE',

    TRANSLATE_UP = 'TRANSLATE_UP',
    TRANSLATE_DOWN = 'TRANSLATE_DOWN',
    TRANSLATE_LEFT = 'TRANSLATE_LEFT',
    TRANSLATE_RIGHT = 'TRANSLATE_RIGHT',
    TOGGLE_TRANSLATE = 'TOGGLE_TRANSLATE',

    SCALE_UP = 'SCALE_UP',
    SCALE_DOWN = 'SCALE_DOWN',
    TOGGLE_SCALE = 'TOGGLE_SCALE',
}


export enum KEY_MODIFIERS {
    SHIFT = 'SHIFT',
    ALT = 'ALT',
    CTRL = 'CTRL',
    META = 'META',
    METACTRL = 'METACTRL',
}



export enum SIZES {
    small = 'small',
    normal = 'normal',
    large = 'large',
}
