export type InternationalizationChinese = 'chinese';
export type InternationalizationEnglish = 'english';
export type InternationalizationFrench = 'french';
export type InternationalizationGerman = 'german';
export type InternationalizationHindi = 'hindi';
export type InternationalizationItalian = 'italian';
export type InternationalizationJapanese = 'japanese';
export type InternationalizationRomanian = 'romanian';
export type InternationalizationRussian = 'russian';
export type InternationalizationSpanish = 'spanish';


export type InternationalizationLanguageType =
    | InternationalizationChinese
    | InternationalizationEnglish
    | InternationalizationFrench
    | InternationalizationGerman
    | InternationalizationHindi
    | InternationalizationItalian
    | InternationalizationJapanese
    | InternationalizationRomanian
    | InternationalizationRussian
    | InternationalizationSpanish;



export type InternationalizationFieldViewcubeFront = 'viewcubeFront';
export type InternationalizationFieldViewcubeBack = 'viewcubeBack';
export type InternationalizationFieldViewcubeLeft = 'viewcubeLeft';
export type InternationalizationFieldViewcubeRight = 'viewcubeRight';
export type InternationalizationFieldViewcubeTop = 'viewcubeTop';
export type InternationalizationFieldViewcubeBase = 'viewcubeBase';

export type InternationalizationFieldToolbarTransformRotate = 'toolbarTransformRotate';
export type InternationalizationFieldToolbarTransformScale = 'toolbarTransformScale';
export type InternationalizationFieldToolbarTransformTranslate = 'toolbarTransformTranslate';

export type InternationalizationFieldToolbarDrawerGlobalTitle = 'toolbarDrawerGlobalTitle';
export type InternationalizationFieldToolbarDrawerGlobalGeneralTheme = 'toolbarDrawerGlobalGeneralTheme';
export type InternationalizationFieldToolbarDrawerGlobalInteractionTheme = 'toolbarDrawerGlobalInteractionTheme';
export type InternationalizationFieldToolbarDrawerGlobalLanguage = 'toolbarDrawerGlobalLanguage';

export type InternationalizationFieldToolbarDrawerTransformTitle = 'toolbarDrawerTransformTitle';
export type InternationalizationFieldToolbarDrawerTransformMultiModeTransform = 'toolbarDrawerTransformMultiModeTransform';
export type InternationalizationFieldToolbarDrawerTransformAllowRotationX = 'toolbarDrawerTransformAllowRotationX';
export type InternationalizationFieldToolbarDrawerTransformAllowRotationY = 'toolbarDrawerTransformAllowRotationY';
export type InternationalizationFieldToolbarDrawerTransformAllowTranslationX = 'toolbarDrawerTransformAllowTranslationX';
export type InternationalizationFieldToolbarDrawerTransformAllowTranslationY = 'toolbarDrawerTransformAllowTranslationY';
export type InternationalizationFieldToolbarDrawerTransformAllowTranslationZ = 'toolbarDrawerTransformAllowTranslationZ';
export type InternationalizationFieldToolbarDrawerTransformAllowScale = 'toolbarDrawerTransformAllowScale';
export type InternationalizationFieldToolbarDrawerTransformTouchTransform = 'toolbarDrawerTransformTouchTransform';

export type InternationalizationFieldToolbarDrawerSpaceTitle = 'toolbarDrawerSpaceTitle';
export type InternationalizationFieldToolbarDrawerSpaceTransparentUserInterface = 'toolbarDrawerSpaceTransparentUserInterface';
export type InternationalizationFieldToolbarDrawerSpaceShowTransformOrigin = 'toolbarDrawerSpaceShowTransformOrigin';
export type InternationalizationFieldToolbarDrawerSpaceTransformOriginSize = 'toolbarDrawerSpaceTransformOriginSize';
export type InternationalizationFieldToolbarDrawerSpacePlaneOpacity = 'toolbarDrawerSpacePlaneOpacity';
export type InternationalizationFieldToolbarDrawerSpaceLayoutType = 'toolbarDrawerSpaceLayoutType';

export type InternationalizationFieldToolbarDrawerToolbarTitle = 'toolbarDrawerToolbarTitle';
export type InternationalizationFieldToolbarDrawerToolbarAlwaysOpaque = 'toolbarDrawerToolbarAlwaysOpaque';
export type InternationalizationFieldToolbarDrawerToolbarShowTransformIcons = 'toolbarDrawerToolbarShowTransformIcons';
export type InternationalizationFieldToolbarDrawerToolbarShowTransformArrows = 'toolbarDrawerToolbarShowTransformArrows';
export type InternationalizationFieldToolbarDrawerToolbarConcealToolbar = 'toolbarDrawerToolbarConcealToolbar';

export type InternationalizationFieldToolbarDrawerViewcubeTitle = 'toolbarDrawerViewcubeTitle';
export type InternationalizationFieldToolbarDrawerViewcubeShowViewcube = 'toolbarDrawerViewcubeShowViewcube';
export type InternationalizationFieldToolbarDrawerViewcubeShowTransformButtons = 'toolbarDrawerViewcubeShowTransformButtons';
export type InternationalizationFieldToolbarDrawerViewcubeAlwaysOpaque = 'toolbarDrawerViewcubeAlwaysOpaque';
export type InternationalizationFieldToolbarDrawerViewcubeConcealViewcube = 'toolbarDrawerViewcubeConcealViewcube';

export type InternationalizationFieldToolbarDrawerTechnicalTitle = 'toolbarDrawerTechnicalTitle';
export type InternationalizationFieldToolbarDrawerTechnicalCullingDistance = 'toolbarDrawerTechnicalCullingDistance';

export type InternationalizationFieldToolbarDrawerShortcutsTitle = 'toolbarDrawerShortcutsTitle';
export type InternationalizationFieldToolbarDrawerShortcutsToggleFirstPerson = 'toolbarDrawerShortcutsToggleFirstPerson';
export type InternationalizationFieldToolbarDrawerShortcutsMoveForward = 'toolbarDrawerShortcutsMoveForward';
export type InternationalizationFieldToolbarDrawerShortcutsMoveBackward = 'toolbarDrawerShortcutsMoveBackward';
export type InternationalizationFieldToolbarDrawerShortcutsMoveLeft = 'toolbarDrawerShortcutsMoveLeft';
export type InternationalizationFieldToolbarDrawerShortcutsMoveRight = 'toolbarDrawerShortcutsMoveRight';
export type InternationalizationFieldToolbarDrawerShortcutsMoveUp = 'toolbarDrawerShortcutsMoveUp';
export type InternationalizationFieldToolbarDrawerShortcutsMoveDown = 'toolbarDrawerShortcutsMoveDown';
export type InternationalizationFieldToolbarDrawerShortcutsTurnLeft = 'toolbarDrawerShortcutsTurnLeft';
export type InternationalizationFieldToolbarDrawerShortcutsTurnRight = 'toolbarDrawerShortcutsTurnRight';
export type InternationalizationFieldToolbarDrawerShortcutsTurnUp = 'toolbarDrawerShortcutsTurnUp';
export type InternationalizationFieldToolbarDrawerShortcutsTurnDown = 'toolbarDrawerShortcutsTurnDown';
export type InternationalizationFieldToolbarDrawerShortcutsRotateUp = 'toolbarDrawerShortcutsRotateUp';
export type InternationalizationFieldToolbarDrawerShortcutsRotateDown = 'toolbarDrawerShortcutsRotateDown';
export type InternationalizationFieldToolbarDrawerShortcutsRotateLeft = 'toolbarDrawerShortcutsRotateLeft';
export type InternationalizationFieldToolbarDrawerShortcutsRotateRight = 'toolbarDrawerShortcutsRotateRight';
export type InternationalizationFieldToolbarDrawerShortcutsToggleRotate = 'toolbarDrawerShortcutsToggleRotate';
export type InternationalizationFieldToolbarDrawerShortcutsTranslateUp = 'toolbarDrawerShortcutsTranslateUp';
export type InternationalizationFieldToolbarDrawerShortcutsTranslateDown = 'toolbarDrawerShortcutsTranslateDown';
export type InternationalizationFieldToolbarDrawerShortcutsTranslateLeft = 'toolbarDrawerShortcutsTranslateLeft';
export type InternationalizationFieldToolbarDrawerShortcutsTranslateRight = 'toolbarDrawerShortcutsTranslateRight';
export type InternationalizationFieldToolbarDrawerShortcutsTranslateIn = 'toolbarDrawerShortcutsTranslateIn';
export type InternationalizationFieldToolbarDrawerShortcutsTranslateOut = 'toolbarDrawerShortcutsTranslateOut';
export type InternationalizationFieldToolbarDrawerShortcutsToggleTranslate = 'toolbarDrawerShortcutsToggleTranslate';
export type InternationalizationFieldToolbarDrawerShortcutsScaleUp = 'toolbarDrawerShortcutsScaleUp';
export type InternationalizationFieldToolbarDrawerShortcutsScaleDown = 'toolbarDrawerShortcutsScaleDown';
export type InternationalizationFieldToolbarDrawerShortcutsToggleScale = 'toolbarDrawerShortcutsToggleScale';

export type InternationalizationFieldToolbarDrawerShortcutsArrowOrScrollUp = 'toolbarDrawerShortcutsArrowOrScrollUp';
export type InternationalizationFieldToolbarDrawerShortcutsArrowOrScrollDown = 'toolbarDrawerShortcutsArrowOrScrollDown';
export type InternationalizationFieldToolbarDrawerShortcutsArrowOrScrollLeft = 'toolbarDrawerShortcutsArrowOrScrollLeft';
export type InternationalizationFieldToolbarDrawerShortcutsArrowOrScrollRight = 'toolbarDrawerShortcutsArrowOrScrollRight';


export type InternationalizationFieldType =
    | InternationalizationFieldViewcubeFront
    | InternationalizationFieldViewcubeBack
    | InternationalizationFieldViewcubeLeft
    | InternationalizationFieldViewcubeRight
    | InternationalizationFieldViewcubeTop
    | InternationalizationFieldViewcubeBase

    | InternationalizationFieldToolbarTransformRotate
    | InternationalizationFieldToolbarTransformScale
    | InternationalizationFieldToolbarTransformTranslate

    | InternationalizationFieldToolbarDrawerGlobalTitle
    | InternationalizationFieldToolbarDrawerGlobalGeneralTheme
    | InternationalizationFieldToolbarDrawerGlobalInteractionTheme
    | InternationalizationFieldToolbarDrawerGlobalLanguage

    | InternationalizationFieldToolbarDrawerTransformTitle
    | InternationalizationFieldToolbarDrawerTransformMultiModeTransform
    | InternationalizationFieldToolbarDrawerTransformAllowRotationX
    | InternationalizationFieldToolbarDrawerTransformAllowRotationY
    | InternationalizationFieldToolbarDrawerTransformAllowTranslationX
    | InternationalizationFieldToolbarDrawerTransformAllowTranslationY
    | InternationalizationFieldToolbarDrawerTransformAllowTranslationZ
    | InternationalizationFieldToolbarDrawerTransformAllowScale
    | InternationalizationFieldToolbarDrawerTransformTouchTransform

    | InternationalizationFieldToolbarDrawerSpaceTitle
    | InternationalizationFieldToolbarDrawerSpaceTransparentUserInterface
    | InternationalizationFieldToolbarDrawerSpaceShowTransformOrigin
    | InternationalizationFieldToolbarDrawerSpaceTransformOriginSize
    | InternationalizationFieldToolbarDrawerSpacePlaneOpacity
    | InternationalizationFieldToolbarDrawerSpaceLayoutType

    | InternationalizationFieldToolbarDrawerToolbarTitle
    | InternationalizationFieldToolbarDrawerToolbarAlwaysOpaque
    | InternationalizationFieldToolbarDrawerToolbarShowTransformIcons
    | InternationalizationFieldToolbarDrawerToolbarShowTransformArrows
    | InternationalizationFieldToolbarDrawerToolbarConcealToolbar

    | InternationalizationFieldToolbarDrawerViewcubeTitle
    | InternationalizationFieldToolbarDrawerViewcubeShowViewcube
    | InternationalizationFieldToolbarDrawerViewcubeShowTransformButtons
    | InternationalizationFieldToolbarDrawerViewcubeAlwaysOpaque
    | InternationalizationFieldToolbarDrawerViewcubeConcealViewcube

    | InternationalizationFieldToolbarDrawerTechnicalTitle
    | InternationalizationFieldToolbarDrawerTechnicalCullingDistance

    | InternationalizationFieldToolbarDrawerShortcutsTitle
    | InternationalizationFieldToolbarDrawerShortcutsToggleFirstPerson
    | InternationalizationFieldToolbarDrawerShortcutsMoveForward
    | InternationalizationFieldToolbarDrawerShortcutsMoveBackward
    | InternationalizationFieldToolbarDrawerShortcutsMoveLeft
    | InternationalizationFieldToolbarDrawerShortcutsMoveRight
    | InternationalizationFieldToolbarDrawerShortcutsMoveUp
    | InternationalizationFieldToolbarDrawerShortcutsMoveDown
    | InternationalizationFieldToolbarDrawerShortcutsTurnLeft
    | InternationalizationFieldToolbarDrawerShortcutsTurnRight
    | InternationalizationFieldToolbarDrawerShortcutsTurnUp
    | InternationalizationFieldToolbarDrawerShortcutsTurnDown
    | InternationalizationFieldToolbarDrawerShortcutsRotateUp
    | InternationalizationFieldToolbarDrawerShortcutsRotateDown
    | InternationalizationFieldToolbarDrawerShortcutsRotateLeft
    | InternationalizationFieldToolbarDrawerShortcutsRotateRight
    | InternationalizationFieldToolbarDrawerShortcutsToggleRotate
    | InternationalizationFieldToolbarDrawerShortcutsTranslateUp
    | InternationalizationFieldToolbarDrawerShortcutsTranslateDown
    | InternationalizationFieldToolbarDrawerShortcutsTranslateLeft
    | InternationalizationFieldToolbarDrawerShortcutsTranslateRight
    | InternationalizationFieldToolbarDrawerShortcutsTranslateIn
    | InternationalizationFieldToolbarDrawerShortcutsTranslateOut
    | InternationalizationFieldToolbarDrawerShortcutsToggleTranslate
    | InternationalizationFieldToolbarDrawerShortcutsScaleUp
    | InternationalizationFieldToolbarDrawerShortcutsScaleDown
    | InternationalizationFieldToolbarDrawerShortcutsToggleScale
    | InternationalizationFieldToolbarDrawerShortcutsArrowOrScrollUp
    | InternationalizationFieldToolbarDrawerShortcutsArrowOrScrollDown
    | InternationalizationFieldToolbarDrawerShortcutsArrowOrScrollLeft
    | InternationalizationFieldToolbarDrawerShortcutsArrowOrScrollRight;


export interface InternationalizationFields {
    viewcubeFront: InternationalizationFieldViewcubeFront;
    viewcubeBack: InternationalizationFieldViewcubeBack;
    viewcubeLeft: InternationalizationFieldViewcubeLeft;
    viewcubeRight: InternationalizationFieldViewcubeRight;
    viewcubeTop: InternationalizationFieldViewcubeTop;
    viewcubeBase: InternationalizationFieldViewcubeBase;

    toolbarTransformRotate: InternationalizationFieldToolbarTransformRotate;
    toolbarTransformScale: InternationalizationFieldToolbarTransformScale;
    toolbarTransformTranslate: InternationalizationFieldToolbarTransformTranslate;

    toolbarDrawerGlobalTitle: InternationalizationFieldToolbarDrawerGlobalTitle;
    toolbarDrawerGlobalGeneralTheme: InternationalizationFieldToolbarDrawerGlobalGeneralTheme;
    toolbarDrawerGlobalInteractionTheme: InternationalizationFieldToolbarDrawerGlobalInteractionTheme;
    toolbarDrawerGlobalLanguage: InternationalizationFieldToolbarDrawerGlobalLanguage;

    toolbarDrawerTransformTitle: InternationalizationFieldToolbarDrawerTransformTitle;
    toolbarDrawerTransformMultiModeTransform: InternationalizationFieldToolbarDrawerTransformMultiModeTransform;
    toolbarDrawerTransformAllowRotationX: InternationalizationFieldToolbarDrawerTransformAllowRotationX;
    toolbarDrawerTransformAllowRotationY: InternationalizationFieldToolbarDrawerTransformAllowRotationY;
    toolbarDrawerTransformAllowTranslationX: InternationalizationFieldToolbarDrawerTransformAllowTranslationX;
    toolbarDrawerTransformAllowTranslationY: InternationalizationFieldToolbarDrawerTransformAllowTranslationY;
    toolbarDrawerTransformAllowTranslationZ: InternationalizationFieldToolbarDrawerTransformAllowTranslationZ;
    toolbarDrawerTransformAllowScale: InternationalizationFieldToolbarDrawerTransformAllowScale;
    toolbarDrawerTransformTouchTransform: InternationalizationFieldToolbarDrawerTransformTouchTransform;

    toolbarDrawerSpaceTitle: InternationalizationFieldToolbarDrawerSpaceTitle;
    toolbarDrawerSpaceTransparentUserInterface: InternationalizationFieldToolbarDrawerSpaceTransparentUserInterface;
    toolbarDrawerSpaceShowTransformOrigin: InternationalizationFieldToolbarDrawerSpaceShowTransformOrigin;
    toolbarDrawerSpaceTransformOriginSize: InternationalizationFieldToolbarDrawerSpaceTransformOriginSize;
    toolbarDrawerSpacePlaneOpacity: InternationalizationFieldToolbarDrawerSpacePlaneOpacity;
    toolbarDrawerSpaceLayoutType: InternationalizationFieldToolbarDrawerSpaceLayoutType;

    toolbarDrawerToolbarTitle: InternationalizationFieldToolbarDrawerToolbarTitle;
    toolbarDrawerToolbarAlwaysOpaque: InternationalizationFieldToolbarDrawerToolbarAlwaysOpaque;
    toolbarDrawerToolbarShowTransformIcons: InternationalizationFieldToolbarDrawerToolbarShowTransformIcons;
    toolbarDrawerToolbarShowTransformArrows: InternationalizationFieldToolbarDrawerToolbarShowTransformArrows;
    toolbarDrawerToolbarConcealToolbar: InternationalizationFieldToolbarDrawerToolbarConcealToolbar;

    toolbarDrawerViewcubeTitle: InternationalizationFieldToolbarDrawerViewcubeTitle;
    toolbarDrawerViewcubeShowViewcube: InternationalizationFieldToolbarDrawerViewcubeShowViewcube;
    toolbarDrawerViewcubeShowTransformButtons: InternationalizationFieldToolbarDrawerViewcubeShowTransformButtons;
    toolbarDrawerViewcubeAlwaysOpaque: InternationalizationFieldToolbarDrawerViewcubeAlwaysOpaque;
    toolbarDrawerViewcubeConcealViewcube: InternationalizationFieldToolbarDrawerViewcubeConcealViewcube;

    toolbarDrawerTechnicalTitle: InternationalizationFieldToolbarDrawerTechnicalTitle;
    toolbarDrawerTechnicalCullingDistance: InternationalizationFieldToolbarDrawerTechnicalCullingDistance;

    toolbarDrawerShortcutsTitle: InternationalizationFieldToolbarDrawerShortcutsTitle;
    toolbarDrawerShortcutsToggleFirstPerson: InternationalizationFieldToolbarDrawerShortcutsToggleFirstPerson;
    toolbarDrawerShortcutsMoveForward: InternationalizationFieldToolbarDrawerShortcutsMoveForward;
    toolbarDrawerShortcutsMoveBackward: InternationalizationFieldToolbarDrawerShortcutsMoveBackward;
    toolbarDrawerShortcutsMoveLeft: InternationalizationFieldToolbarDrawerShortcutsMoveLeft;
    toolbarDrawerShortcutsMoveRight: InternationalizationFieldToolbarDrawerShortcutsMoveRight;
    toolbarDrawerShortcutsMoveUp: InternationalizationFieldToolbarDrawerShortcutsMoveUp;
    toolbarDrawerShortcutsMoveDown: InternationalizationFieldToolbarDrawerShortcutsMoveDown;
    toolbarDrawerShortcutsTurnLeft: InternationalizationFieldToolbarDrawerShortcutsTurnLeft;
    toolbarDrawerShortcutsTurnRight: InternationalizationFieldToolbarDrawerShortcutsTurnRight;
    toolbarDrawerShortcutsTurnUp: InternationalizationFieldToolbarDrawerShortcutsTurnUp;
    toolbarDrawerShortcutsTurnDown: InternationalizationFieldToolbarDrawerShortcutsTurnDown;
    toolbarDrawerShortcutsRotateUp: InternationalizationFieldToolbarDrawerShortcutsRotateUp;
    toolbarDrawerShortcutsRotateDown: InternationalizationFieldToolbarDrawerShortcutsRotateDown;
    toolbarDrawerShortcutsRotateLeft: InternationalizationFieldToolbarDrawerShortcutsRotateLeft;
    toolbarDrawerShortcutsRotateRight: InternationalizationFieldToolbarDrawerShortcutsRotateRight;
    toolbarDrawerShortcutsToggleRotate: InternationalizationFieldToolbarDrawerShortcutsToggleRotate;
    toolbarDrawerShortcutsTranslateUp: InternationalizationFieldToolbarDrawerShortcutsTranslateUp;
    toolbarDrawerShortcutsTranslateDown: InternationalizationFieldToolbarDrawerShortcutsTranslateDown;
    toolbarDrawerShortcutsTranslateLeft: InternationalizationFieldToolbarDrawerShortcutsTranslateLeft;
    toolbarDrawerShortcutsTranslateRight: InternationalizationFieldToolbarDrawerShortcutsTranslateRight;
    toolbarDrawerShortcutsTranslateIn: InternationalizationFieldToolbarDrawerShortcutsTranslateIn;
    toolbarDrawerShortcutsTranslateOut: InternationalizationFieldToolbarDrawerShortcutsTranslateOut;
    toolbarDrawerShortcutsToggleTranslate: InternationalizationFieldToolbarDrawerShortcutsToggleTranslate;
    toolbarDrawerShortcutsScaleUp: InternationalizationFieldToolbarDrawerShortcutsScaleUp;
    toolbarDrawerShortcutsScaleDown: InternationalizationFieldToolbarDrawerShortcutsScaleDown;
    toolbarDrawerShortcutsToggleScale: InternationalizationFieldToolbarDrawerShortcutsToggleScale;

    toolbarDrawerShortcutsArrowOrScrollUp: InternationalizationFieldToolbarDrawerShortcutsArrowOrScrollUp;
    toolbarDrawerShortcutsArrowOrScrollDown: InternationalizationFieldToolbarDrawerShortcutsArrowOrScrollDown;
    toolbarDrawerShortcutsArrowOrScrollLeft: InternationalizationFieldToolbarDrawerShortcutsArrowOrScrollLeft;
    toolbarDrawerShortcutsArrowOrScrollRight: InternationalizationFieldToolbarDrawerShortcutsArrowOrScrollRight;
}


export type Internationalization = Record<InternationalizationFieldType, string>;
