#!/usr/bin/env node
/**
 * Generate the documentation tables that must not drift from the code:
 *
 *   docs/SHORTCUTS.md  from `PLURID_SHORTCUTS` / `PLURID_POINTER_GESTURES` / `PLURID_SHORTCUT_GROUP_TITLES`
 *                      in @plurid/plurid-data (the bindings the engine dispatches, the `?` overlay shows);
 *   docs/HARNESS.md    from the render-test harness's FLAG REGISTRY (`fixtures/render-test/src/harness/flags.ts`)
 *                      and FIXTURE CATALOG (`fixtures/render-test/src/fixtures/catalog.ts`) — every `?flag=`
 *                      the harness understands and every fixture the browser suites verify.
 *
 *   pnpm docs.tables          # rewrite both (needs `pnpm --filter @plurid/plurid-data build`; Node ≥ 23.6 imports the .ts registries directly)
 *   pnpm docs.tables --check  # exit 1 when either file is stale (part of `pnpm verify`)
 */
import { createRequire } from 'node:module';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const require = createRequire(import.meta.url);
const check = process.argv.includes('--check');

const emit = (relative, output, summary) => {
    const target = resolve(root, relative);
    if (check) {
        const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
        if (current !== output) {
            console.error('[docs.tables] ' + relative + ' is stale — run `pnpm docs.tables`');
            process.exit(1);
        }
        console.log('[docs.tables] ' + relative + ' is current');
    } else {
        writeFileSync(target, output);
        console.log('[docs.tables] wrote ' + relative + ' (' + summary + ')');
    }
};


// #region shortcuts
const dataPackage = resolve(root, 'packages/plurid-web/plurid-core/plurid-data');
const distribution = resolve(dataPackage, 'distribution/index.js');

if (!existsSync(distribution)) {
    console.error('[docs.tables] build @plurid/plurid-data first: pnpm --filter @plurid/plurid-data build');
    process.exit(1);
}

const data = require(distribution);
const shortcuts = data.PLURID_SHORTCUTS;
const gestures = data.PLURID_POINTER_GESTURES;
const titles = data.PLURID_SHORTCUT_GROUP_TITLES || {};

const label = (code) => {
    const names = {
        Space: 'Space', Escape: 'Esc', Tab: 'Tab', Period: '.', Comma: ',', Slash: '/', Backslash: '\\',
        Minus: '-', Equal: '=', ShiftLeft: 'Shift', ShiftRight: 'Shift', Enter: 'Enter', Home: 'Home', End: 'End',
        ArrowUp: '↑', ArrowDown: '↓', ArrowLeft: '←', ArrowRight: '→',
    };
    if (names[code]) return names[code];
    if (/^Key.$/.test(code)) return code.slice(3);
    if (/^Digit.$/.test(code)) return code.slice(5);
    return code;
};

const keysOf = (definition) => {
    const parts = [];
    if (definition.modifiers?.ctrlOrMeta) parts.push('⌘/Ctrl');
    if (definition.modifiers?.alt) parts.push('Alt');
    if (definition.modifiers?.shift) parts.push('Shift');
    if (definition.keys) parts.push(...definition.keys);
    else if (definition.code) parts.push(label(definition.code));
    return parts.map((part) => '`' + part + '`').join(' + ');
};

const groups = new Map();
for (const definition of shortcuts) {
    const list = groups.get(definition.group) || [];
    list.push(definition);
    groups.set(definition.group, list);
}

const shortcutLines = [];
shortcutLines.push('# Keyboard shortcuts and pointer gestures');
shortcutLines.push('');
shortcutLines.push('GENERATED by `scripts/generate-tables.mjs` from `PLURID_SHORTCUTS` / `PLURID_POINTER_GESTURES` in `@plurid/plurid-data` — do not edit; run `pnpm docs.tables`. Every shortcut can be disabled or remapped through `space.shortcuts` (see CONTROL_SURFACE.md); `hold` shortcuts act while the key is down; `when` names the mode the shortcut needs.');
shortcutLines.push('');
for (const [group, list] of groups) {
    shortcutLines.push('## ' + (titles[group] || group));
    shortcutLines.push('');
    shortcutLines.push('| Keys | Action | Id | Kind | When |');
    shortcutLines.push('| --- | --- | --- | --- | --- |');
    for (const definition of list) {
        shortcutLines.push(`| ${keysOf(definition)} | ${definition.label} | \`${definition.id}\` | ${definition.kind} | ${definition.when || '-'} |`);
    }
    shortcutLines.push('');
}
shortcutLines.push('## Pointer');
shortcutLines.push('');
shortcutLines.push('| Input | Action |');
shortcutLines.push('| --- | --- |');
for (const gesture of gestures) {
    shortcutLines.push(`| ${gesture.keys.map((key) => '`' + key + '`').join(' + ')} | ${gesture.label} |`);
}
shortcutLines.push('');

emit('docs/SHORTCUTS.md', shortcutLines.join('\n'), shortcuts.length + ' shortcuts, ' + gestures.length + ' gestures');
// #endregion shortcuts


// #region harness
const harness = resolve(root, 'fixtures/render-test/src');
const { FLAGS } = await import(pathToFileURL(resolve(harness, 'harness/flags.ts')).href);
const { FIXTURES } = await import(pathToFileURL(resolve(harness, 'fixtures/catalog.ts')).href);

const cell = (text) => String(text ?? '').replace(/\|/g, '\\|');
const flagGroups = new Map();
for (const flag of FLAGS) {
    const list = flagGroups.get(flag.group) || [];
    list.push(flag);
    flagGroups.set(flag.group, list);
}
const paramOf = (flag) => {
    if (flag.type === 'boolean') return '`?' + flag.key + '=' + (flag.on ?? '1') + '`';
    if (flag.type === 'enum') return '`?' + flag.key + '=' + flag.values.join('\\|') + '`';
    if (flag.type === 'number') return '`?' + flag.key + '=<n>`';
    return '`?' + flag.key + '=<text>`';
};

const harnessLines = [];
harnessLines.push('# The render-test harness: flags and fixtures');
harnessLines.push('');
harnessLines.push('GENERATED by `scripts/generate-tables.mjs` from `fixtures/render-test/src/harness/flags.ts` (the flag registry) and `fixtures/render-test/src/fixtures/catalog.ts` (the fixture catalog) — do not edit; run `pnpm docs.tables`.');
harnessLines.push('');
harnessLines.push('THE URL IS THE FIXTURE. Every option of the harness (`fixtures/render-test`, `pnpm --filter plurid-render-test dev`) is a query flag; the SETUP button at the top-left expands into all of them — the layout switches on the live instance, the plane set / sizes / persistence re-create the application, everything else reloads the page — and rewrites the URL, so any state is shareable by pasting a link. A named FIXTURE is a set of flags (`?fixture=<name>`; its flags apply UNDER any explicit param, so a scenario can open a fixture and override one flag), optional link clicks, and the viewpoints the visual baselines are taken at. `?gallery=1` renders every fixture on one page (each in its own harness).');
harnessLines.push('');
harnessLines.push('## Flags');
harnessLines.push('');
harnessLines.push('`Applies` — `live`: the configuration prop of the mounted application; `remount`: a new application (no page load); `reload`: a page load (a startup-only option).');
harnessLines.push('');
for (const [group, list] of flagGroups) {
    harnessLines.push('### ' + group);
    harnessLines.push('');
    harnessLines.push('| Param | Default | Applies | Does | Exercises |');
    harnessLines.push('| --- | --- | --- | --- | --- |');
    for (const flag of list) {
        harnessLines.push(`| ${paramOf(flag)} | ${flag.default === undefined ? '-' : '`' + cell(flag.default) + '`'} | ${flag.apply} | ${cell(flag.description)} | ${cell(flag.exercises)} |`);
    }
    harnessLines.push('');
}
harnessLines.push('## Fixtures');
harnessLines.push('');
harnessLines.push('Verified by `fixtures/render-test/e2e/fixtures.spec.ts` (the generic invariants: boots without console errors, every shown plane measured, a declared size is the plane\'s box, the roots of a grid layout do not overlap in world X/Y, one minimap dot per shown plane, every on-screen link hit by itself, the space idle) and `visual.spec.ts` (a screenshot baseline per viewpoint under `e2e/__snapshots__/<platform>/`, compared strictly with `VISUAL_STRICT=1`; regenerate with `npx playwright test --config e2e/playwright.config.ts --project visual --update-snapshots` from `fixtures/render-test`).');
harnessLines.push('');
harnessLines.push('| Fixture | Title | Flags | Steps | Viewpoints | Expectations |');
harnessLines.push('| --- | --- | --- | --- | --- | --- |');
for (const fixture of FIXTURES) {
    const flags = Object.entries(fixture.query).map(([key, value]) => '`' + key + '=' + value + '`').join(' ') || '-';
    const steps = (fixture.steps || []).map((step) => '`' + step.plane + ' → ' + step.route + '`').join(', ') || '-';
    const viewpoints = fixture.viewpoints.map((viewpoint) => '`' + viewpoint.name + '`').join(', ');
    const expectations = Object.entries(fixture.expect || {}).map(([key, value]) => key + ': ' + value).join(', ') || '-';
    harnessLines.push(`| \`${fixture.name}\` | ${cell(fixture.title)} — ${cell(fixture.description)} | ${flags} | ${steps} | ${viewpoints} | ${cell(expectations)} |`);
}
harnessLines.push('');
harnessLines.push('## Assertion globals');
harnessLines.push('');
harnessLines.push('Published on `window` once the application is ready (`src/harness/globals.ts`): `__pluridApi` (the `onReady` api), `__rtCamera()` (the live camera), `__rtTree()` (the live space tree), `__rtViewpoint2()` (the v2 viewpoint), `__rtFlags()` (the parsed flags), `__rtPlanes()` (the declared sizes by route), `__rtPerf` (dispatch / frame counters), `__rtChanges` (the changed slice keys per store notification), `__rtBench` (`?bench=1`), `__rtRootsSize()` (the roots container\'s applied size), `__rtUnhandled` (unhandled key codes), `__rtStore` (the memory adapter\'s map), `__rtViewpoint` / `__rtContent` / `__rtRestored` (the persistence callbacks), `__rtPlaneLens` / `__rtMediaImageLoaded` (`?media=1`).');
harnessLines.push('');

emit('docs/HARNESS.md', harnessLines.join('\n'), FLAGS.length + ' flags, ' + FIXTURES.length + ' fixtures');
// #endregion harness
