#!/usr/bin/env node
/**
 * Generate `docs/SHORTCUTS.md` from the data tables (`PLURID_SHORTCUTS`, `PLURID_POINTER_GESTURES`,
 * `PLURID_SHORTCUT_GROUP_TITLES` in @plurid/plurid-data), so the documented bindings cannot drift
 * from the ones the engine dispatches, the `?` overlay shows and the toolbar drawer lists.
 *
 *   pnpm docs.tables          # rewrite docs/SHORTCUTS.md (needs `pnpm --filter @plurid/plurid-data build`)
 *   pnpm docs.tables --check  # exit 1 when the file is stale (CI)
 */
import { createRequire } from 'node:module';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const require = createRequire(import.meta.url);
const dataPackage = resolve(root, 'packages/plurid-web/plurid-core/plurid-data');
const distribution = resolve(dataPackage, 'distribution/index.js');

if (!existsSync(distribution)) {
    console.error('[docs.tables] build @plurid/plurid-data first: pnpm --filter @plurid/plurid-data build');
    process.exit(1);
}

const data = require(distribution);
const shortcuts = data.PLURID_SHORTCUTS;
const gestures = data.PLURID_POINTER_GESTURES;
const titles = data.PLURID_SHORTCUT_GROUP_TITLES || {};

const label = (code) => {
    const names = {
        Space: 'Space', Escape: 'Esc', Tab: 'Tab', Period: '.', Comma: ',', Slash: '/', Backslash: '\\',
        Minus: '-', Equal: '=', ShiftLeft: 'Shift', ShiftRight: 'Shift', Enter: 'Enter', Home: 'Home', End: 'End',
        ArrowUp: '↑', ArrowDown: '↓', ArrowLeft: '←', ArrowRight: '→',
    };
    if (names[code]) return names[code];
    if (/^Key.$/.test(code)) return code.slice(3);
    if (/^Digit.$/.test(code)) return code.slice(5);
    return code;
};

const keysOf = (definition) => {
    const parts = [];
    if (definition.modifiers?.ctrlOrMeta) parts.push('⌘/Ctrl');
    if (definition.modifiers?.alt) parts.push('Alt');
    if (definition.modifiers?.shift) parts.push('Shift');
    if (definition.keys) parts.push(...definition.keys);
    else if (definition.code) parts.push(label(definition.code));
    return parts.map((part) => '`' + part + '`').join(' + ');
};

const groups = new Map();
for (const definition of shortcuts) {
    const list = groups.get(definition.group) || [];
    list.push(definition);
    groups.set(definition.group, list);
}

const lines = [];
lines.push('# Keyboard shortcuts and pointer gestures');
lines.push('');
lines.push('GENERATED by `scripts/generate-tables.mjs` from `PLURID_SHORTCUTS` / `PLURID_POINTER_GESTURES` in `@plurid/plurid-data` — do not edit; run `pnpm docs.tables`. Every shortcut can be disabled or remapped through `space.shortcuts` (see CONTROL_SURFACE.md); `hold` shortcuts act while the key is down; `when` names the mode the shortcut needs.');
lines.push('');
for (const [group, list] of groups) {
    lines.push('## ' + (titles[group] || group));
    lines.push('');
    lines.push('| Keys | Action | Id | Kind | When |');
    lines.push('| --- | --- | --- | --- | --- |');
    for (const definition of list) {
        lines.push(`| ${keysOf(definition)} | ${definition.label} | \`${definition.id}\` | ${definition.kind} | ${definition.when || '-'} |`);
    }
    lines.push('');
}
lines.push('## Pointer');
lines.push('');
lines.push('| Input | Action |');
lines.push('| --- | --- |');
for (const gesture of gestures) {
    lines.push(`| ${gesture.keys.map((key) => '`' + key + '`').join(' + ')} | ${gesture.label} |`);
}
lines.push('');

const output = lines.join('\n');
const target = resolve(root, 'docs/SHORTCUTS.md');
const check = process.argv.includes('--check');
if (check) {
    const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
    if (current !== output) {
        console.error('[docs.tables] docs/SHORTCUTS.md is stale — run `pnpm docs.tables`');
        process.exit(1);
    }
    console.log('[docs.tables] docs/SHORTCUTS.md is current');
} else {
    writeFileSync(target, output);
    console.log('[docs.tables] wrote docs/SHORTCUTS.md (' + shortcuts.length + ' shortcuts, ' + gestures.length + ' gestures)');
}
