/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface PluridBranch {}
  interface PluridBranchAttributes extends StencilHTMLAttributes {}

  interface PluridBridge {}
  interface PluridBridgeAttributes extends StencilHTMLAttributes {}

  interface PluridContainer {}
  interface PluridContainerAttributes extends StencilHTMLAttributes {}

  interface PluridContent {}
  interface PluridContentAttributes extends StencilHTMLAttributes {}

  interface PluridControls {}
  interface PluridControlsAttributes extends StencilHTMLAttributes {}

  interface PluridLink {}
  interface PluridLinkAttributes extends StencilHTMLAttributes {}

  interface PluridOptions {}
  interface PluridOptionsAttributes extends StencilHTMLAttributes {}

  interface PluridPage {}
  interface PluridPageAttributes extends StencilHTMLAttributes {}

  interface PluridShadow {}
  interface PluridShadowAttributes extends StencilHTMLAttributes {}

  interface PluridSheet {}
  interface PluridSheetAttributes extends StencilHTMLAttributes {}

  interface PluridSolid {}
  interface PluridSolidAttributes extends StencilHTMLAttributes {}

  interface PluridSpace {}
  interface PluridSpaceAttributes extends StencilHTMLAttributes {}

  interface PluridViewcube {}
  interface PluridViewcubeAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'PluridBranch': Components.PluridBranch;
    'PluridBridge': Components.PluridBridge;
    'PluridContainer': Components.PluridContainer;
    'PluridContent': Components.PluridContent;
    'PluridControls': Components.PluridControls;
    'PluridLink': Components.PluridLink;
    'PluridOptions': Components.PluridOptions;
    'PluridPage': Components.PluridPage;
    'PluridShadow': Components.PluridShadow;
    'PluridSheet': Components.PluridSheet;
    'PluridSolid': Components.PluridSolid;
    'PluridSpace': Components.PluridSpace;
    'PluridViewcube': Components.PluridViewcube;
  }

  interface StencilIntrinsicElements {
    'plurid-branch': Components.PluridBranchAttributes;
    'plurid-bridge': Components.PluridBridgeAttributes;
    'plurid-container': Components.PluridContainerAttributes;
    'plurid-content': Components.PluridContentAttributes;
    'plurid-controls': Components.PluridControlsAttributes;
    'plurid-link': Components.PluridLinkAttributes;
    'plurid-options': Components.PluridOptionsAttributes;
    'plurid-page': Components.PluridPageAttributes;
    'plurid-shadow': Components.PluridShadowAttributes;
    'plurid-sheet': Components.PluridSheetAttributes;
    'plurid-solid': Components.PluridSolidAttributes;
    'plurid-space': Components.PluridSpaceAttributes;
    'plurid-viewcube': Components.PluridViewcubeAttributes;
  }


  interface HTMLPluridBranchElement extends Components.PluridBranch, HTMLStencilElement {}
  var HTMLPluridBranchElement: {
    prototype: HTMLPluridBranchElement;
    new (): HTMLPluridBranchElement;
  };

  interface HTMLPluridBridgeElement extends Components.PluridBridge, HTMLStencilElement {}
  var HTMLPluridBridgeElement: {
    prototype: HTMLPluridBridgeElement;
    new (): HTMLPluridBridgeElement;
  };

  interface HTMLPluridContainerElement extends Components.PluridContainer, HTMLStencilElement {}
  var HTMLPluridContainerElement: {
    prototype: HTMLPluridContainerElement;
    new (): HTMLPluridContainerElement;
  };

  interface HTMLPluridContentElement extends Components.PluridContent, HTMLStencilElement {}
  var HTMLPluridContentElement: {
    prototype: HTMLPluridContentElement;
    new (): HTMLPluridContentElement;
  };

  interface HTMLPluridControlsElement extends Components.PluridControls, HTMLStencilElement {}
  var HTMLPluridControlsElement: {
    prototype: HTMLPluridControlsElement;
    new (): HTMLPluridControlsElement;
  };

  interface HTMLPluridLinkElement extends Components.PluridLink, HTMLStencilElement {}
  var HTMLPluridLinkElement: {
    prototype: HTMLPluridLinkElement;
    new (): HTMLPluridLinkElement;
  };

  interface HTMLPluridOptionsElement extends Components.PluridOptions, HTMLStencilElement {}
  var HTMLPluridOptionsElement: {
    prototype: HTMLPluridOptionsElement;
    new (): HTMLPluridOptionsElement;
  };

  interface HTMLPluridPageElement extends Components.PluridPage, HTMLStencilElement {}
  var HTMLPluridPageElement: {
    prototype: HTMLPluridPageElement;
    new (): HTMLPluridPageElement;
  };

  interface HTMLPluridShadowElement extends Components.PluridShadow, HTMLStencilElement {}
  var HTMLPluridShadowElement: {
    prototype: HTMLPluridShadowElement;
    new (): HTMLPluridShadowElement;
  };

  interface HTMLPluridSheetElement extends Components.PluridSheet, HTMLStencilElement {}
  var HTMLPluridSheetElement: {
    prototype: HTMLPluridSheetElement;
    new (): HTMLPluridSheetElement;
  };

  interface HTMLPluridSolidElement extends Components.PluridSolid, HTMLStencilElement {}
  var HTMLPluridSolidElement: {
    prototype: HTMLPluridSolidElement;
    new (): HTMLPluridSolidElement;
  };

  interface HTMLPluridSpaceElement extends Components.PluridSpace, HTMLStencilElement {}
  var HTMLPluridSpaceElement: {
    prototype: HTMLPluridSpaceElement;
    new (): HTMLPluridSpaceElement;
  };

  interface HTMLPluridViewcubeElement extends Components.PluridViewcube, HTMLStencilElement {}
  var HTMLPluridViewcubeElement: {
    prototype: HTMLPluridViewcubeElement;
    new (): HTMLPluridViewcubeElement;
  };

  interface HTMLElementTagNameMap {
    'plurid-branch': HTMLPluridBranchElement
    'plurid-bridge': HTMLPluridBridgeElement
    'plurid-container': HTMLPluridContainerElement
    'plurid-content': HTMLPluridContentElement
    'plurid-controls': HTMLPluridControlsElement
    'plurid-link': HTMLPluridLinkElement
    'plurid-options': HTMLPluridOptionsElement
    'plurid-page': HTMLPluridPageElement
    'plurid-shadow': HTMLPluridShadowElement
    'plurid-sheet': HTMLPluridSheetElement
    'plurid-solid': HTMLPluridSolidElement
    'plurid-space': HTMLPluridSpaceElement
    'plurid-viewcube': HTMLPluridViewcubeElement
  }

  interface ElementTagNameMap {
    'plurid-branch': HTMLPluridBranchElement;
    'plurid-bridge': HTMLPluridBridgeElement;
    'plurid-container': HTMLPluridContainerElement;
    'plurid-content': HTMLPluridContentElement;
    'plurid-controls': HTMLPluridControlsElement;
    'plurid-link': HTMLPluridLinkElement;
    'plurid-options': HTMLPluridOptionsElement;
    'plurid-page': HTMLPluridPageElement;
    'plurid-shadow': HTMLPluridShadowElement;
    'plurid-sheet': HTMLPluridSheetElement;
    'plurid-solid': HTMLPluridSolidElement;
    'plurid-space': HTMLPluridSpaceElement;
    'plurid-viewcube': HTMLPluridViewcubeElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
