/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface PluridApp {
    'theme': string;
  }
  interface PluridAppAttributes extends StencilHTMLAttributes {
    'theme'?: string;
  }

  interface PluridBranch {
    'link': string;
  }
  interface PluridBranchAttributes extends StencilHTMLAttributes {
    'link'?: string;
  }

  interface PluridBridge {}
  interface PluridBridgeAttributes extends StencilHTMLAttributes {}

  interface PluridContainer {}
  interface PluridContainerAttributes extends StencilHTMLAttributes {}

  interface PluridContent {}
  interface PluridContentAttributes extends StencilHTMLAttributes {}

  interface PluridControls {}
  interface PluridControlsAttributes extends StencilHTMLAttributes {}

  interface PluridDocument {}
  interface PluridDocumentAttributes extends StencilHTMLAttributes {}

  interface PluridOptions {}
  interface PluridOptionsAttributes extends StencilHTMLAttributes {}

  interface PluridPage {
    'name': string;
    'pageTitle': string;
  }
  interface PluridPageAttributes extends StencilHTMLAttributes {
    'name'?: string;
    'pageTitle'?: string;
  }

  interface PluridRoot {}
  interface PluridRootAttributes extends StencilHTMLAttributes {}

  interface PluridRoots {}
  interface PluridRootsAttributes extends StencilHTMLAttributes {}

  interface PluridScion {}
  interface PluridScionAttributes extends StencilHTMLAttributes {}

  interface PluridShadow {
    'sheet': string;
  }
  interface PluridShadowAttributes extends StencilHTMLAttributes {
    'sheet'?: string;
  }

  interface PluridSheet {}
  interface PluridSheetAttributes extends StencilHTMLAttributes {}

  interface PluridSolid {}
  interface PluridSolidAttributes extends StencilHTMLAttributes {}

  interface PluridSpace {}
  interface PluridSpaceAttributes extends StencilHTMLAttributes {}

  interface PluridViewcube {}
  interface PluridViewcubeAttributes extends StencilHTMLAttributes {}

  interface PluridButton {}
  interface PluridButtonAttributes extends StencilHTMLAttributes {}

  interface PluridLink {
    'active': boolean;
    'name': string;
    'page': string;
    'samepage': boolean;
  }
  interface PluridLinkAttributes extends StencilHTMLAttributes {
    'active'?: boolean;
    'name'?: string;
    'page'?: string;
    'samepage'?: boolean;
  }

  interface PluridRoute {}
  interface PluridRouteAttributes extends StencilHTMLAttributes {}

  interface PluridRouter {}
  interface PluridRouterAttributes extends StencilHTMLAttributes {}

  interface PluridRoutes {}
  interface PluridRoutesAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'PluridApp': Components.PluridApp;
    'PluridBranch': Components.PluridBranch;
    'PluridBridge': Components.PluridBridge;
    'PluridContainer': Components.PluridContainer;
    'PluridContent': Components.PluridContent;
    'PluridControls': Components.PluridControls;
    'PluridDocument': Components.PluridDocument;
    'PluridOptions': Components.PluridOptions;
    'PluridPage': Components.PluridPage;
    'PluridRoot': Components.PluridRoot;
    'PluridRoots': Components.PluridRoots;
    'PluridScion': Components.PluridScion;
    'PluridShadow': Components.PluridShadow;
    'PluridSheet': Components.PluridSheet;
    'PluridSolid': Components.PluridSolid;
    'PluridSpace': Components.PluridSpace;
    'PluridViewcube': Components.PluridViewcube;
    'PluridButton': Components.PluridButton;
    'PluridLink': Components.PluridLink;
    'PluridRoute': Components.PluridRoute;
    'PluridRouter': Components.PluridRouter;
    'PluridRoutes': Components.PluridRoutes;
  }

  interface StencilIntrinsicElements {
    'plurid-app': Components.PluridAppAttributes;
    'plurid-branch': Components.PluridBranchAttributes;
    'plurid-bridge': Components.PluridBridgeAttributes;
    'plurid-container': Components.PluridContainerAttributes;
    'plurid-content': Components.PluridContentAttributes;
    'plurid-controls': Components.PluridControlsAttributes;
    'plurid-document': Components.PluridDocumentAttributes;
    'plurid-options': Components.PluridOptionsAttributes;
    'plurid-page': Components.PluridPageAttributes;
    'plurid-root': Components.PluridRootAttributes;
    'plurid-roots': Components.PluridRootsAttributes;
    'plurid-scion': Components.PluridScionAttributes;
    'plurid-shadow': Components.PluridShadowAttributes;
    'plurid-sheet': Components.PluridSheetAttributes;
    'plurid-solid': Components.PluridSolidAttributes;
    'plurid-space': Components.PluridSpaceAttributes;
    'plurid-viewcube': Components.PluridViewcubeAttributes;
    'plurid-button': Components.PluridButtonAttributes;
    'plurid-link': Components.PluridLinkAttributes;
    'plurid-route': Components.PluridRouteAttributes;
    'plurid-router': Components.PluridRouterAttributes;
    'plurid-routes': Components.PluridRoutesAttributes;
  }


  interface HTMLPluridAppElement extends Components.PluridApp, HTMLStencilElement {}
  var HTMLPluridAppElement: {
    prototype: HTMLPluridAppElement;
    new (): HTMLPluridAppElement;
  };

  interface HTMLPluridBranchElement extends Components.PluridBranch, HTMLStencilElement {}
  var HTMLPluridBranchElement: {
    prototype: HTMLPluridBranchElement;
    new (): HTMLPluridBranchElement;
  };

  interface HTMLPluridBridgeElement extends Components.PluridBridge, HTMLStencilElement {}
  var HTMLPluridBridgeElement: {
    prototype: HTMLPluridBridgeElement;
    new (): HTMLPluridBridgeElement;
  };

  interface HTMLPluridContainerElement extends Components.PluridContainer, HTMLStencilElement {}
  var HTMLPluridContainerElement: {
    prototype: HTMLPluridContainerElement;
    new (): HTMLPluridContainerElement;
  };

  interface HTMLPluridContentElement extends Components.PluridContent, HTMLStencilElement {}
  var HTMLPluridContentElement: {
    prototype: HTMLPluridContentElement;
    new (): HTMLPluridContentElement;
  };

  interface HTMLPluridControlsElement extends Components.PluridControls, HTMLStencilElement {}
  var HTMLPluridControlsElement: {
    prototype: HTMLPluridControlsElement;
    new (): HTMLPluridControlsElement;
  };

  interface HTMLPluridDocumentElement extends Components.PluridDocument, HTMLStencilElement {}
  var HTMLPluridDocumentElement: {
    prototype: HTMLPluridDocumentElement;
    new (): HTMLPluridDocumentElement;
  };

  interface HTMLPluridOptionsElement extends Components.PluridOptions, HTMLStencilElement {}
  var HTMLPluridOptionsElement: {
    prototype: HTMLPluridOptionsElement;
    new (): HTMLPluridOptionsElement;
  };

  interface HTMLPluridPageElement extends Components.PluridPage, HTMLStencilElement {}
  var HTMLPluridPageElement: {
    prototype: HTMLPluridPageElement;
    new (): HTMLPluridPageElement;
  };

  interface HTMLPluridRootElement extends Components.PluridRoot, HTMLStencilElement {}
  var HTMLPluridRootElement: {
    prototype: HTMLPluridRootElement;
    new (): HTMLPluridRootElement;
  };

  interface HTMLPluridRootsElement extends Components.PluridRoots, HTMLStencilElement {}
  var HTMLPluridRootsElement: {
    prototype: HTMLPluridRootsElement;
    new (): HTMLPluridRootsElement;
  };

  interface HTMLPluridScionElement extends Components.PluridScion, HTMLStencilElement {}
  var HTMLPluridScionElement: {
    prototype: HTMLPluridScionElement;
    new (): HTMLPluridScionElement;
  };

  interface HTMLPluridShadowElement extends Components.PluridShadow, HTMLStencilElement {}
  var HTMLPluridShadowElement: {
    prototype: HTMLPluridShadowElement;
    new (): HTMLPluridShadowElement;
  };

  interface HTMLPluridSheetElement extends Components.PluridSheet, HTMLStencilElement {}
  var HTMLPluridSheetElement: {
    prototype: HTMLPluridSheetElement;
    new (): HTMLPluridSheetElement;
  };

  interface HTMLPluridSolidElement extends Components.PluridSolid, HTMLStencilElement {}
  var HTMLPluridSolidElement: {
    prototype: HTMLPluridSolidElement;
    new (): HTMLPluridSolidElement;
  };

  interface HTMLPluridSpaceElement extends Components.PluridSpace, HTMLStencilElement {}
  var HTMLPluridSpaceElement: {
    prototype: HTMLPluridSpaceElement;
    new (): HTMLPluridSpaceElement;
  };

  interface HTMLPluridViewcubeElement extends Components.PluridViewcube, HTMLStencilElement {}
  var HTMLPluridViewcubeElement: {
    prototype: HTMLPluridViewcubeElement;
    new (): HTMLPluridViewcubeElement;
  };

  interface HTMLPluridButtonElement extends Components.PluridButton, HTMLStencilElement {}
  var HTMLPluridButtonElement: {
    prototype: HTMLPluridButtonElement;
    new (): HTMLPluridButtonElement;
  };

  interface HTMLPluridLinkElement extends Components.PluridLink, HTMLStencilElement {}
  var HTMLPluridLinkElement: {
    prototype: HTMLPluridLinkElement;
    new (): HTMLPluridLinkElement;
  };

  interface HTMLPluridRouteElement extends Components.PluridRoute, HTMLStencilElement {}
  var HTMLPluridRouteElement: {
    prototype: HTMLPluridRouteElement;
    new (): HTMLPluridRouteElement;
  };

  interface HTMLPluridRouterElement extends Components.PluridRouter, HTMLStencilElement {}
  var HTMLPluridRouterElement: {
    prototype: HTMLPluridRouterElement;
    new (): HTMLPluridRouterElement;
  };

  interface HTMLPluridRoutesElement extends Components.PluridRoutes, HTMLStencilElement {}
  var HTMLPluridRoutesElement: {
    prototype: HTMLPluridRoutesElement;
    new (): HTMLPluridRoutesElement;
  };

  interface HTMLElementTagNameMap {
    'plurid-app': HTMLPluridAppElement
    'plurid-branch': HTMLPluridBranchElement
    'plurid-bridge': HTMLPluridBridgeElement
    'plurid-container': HTMLPluridContainerElement
    'plurid-content': HTMLPluridContentElement
    'plurid-controls': HTMLPluridControlsElement
    'plurid-document': HTMLPluridDocumentElement
    'plurid-options': HTMLPluridOptionsElement
    'plurid-page': HTMLPluridPageElement
    'plurid-root': HTMLPluridRootElement
    'plurid-roots': HTMLPluridRootsElement
    'plurid-scion': HTMLPluridScionElement
    'plurid-shadow': HTMLPluridShadowElement
    'plurid-sheet': HTMLPluridSheetElement
    'plurid-solid': HTMLPluridSolidElement
    'plurid-space': HTMLPluridSpaceElement
    'plurid-viewcube': HTMLPluridViewcubeElement
    'plurid-button': HTMLPluridButtonElement
    'plurid-link': HTMLPluridLinkElement
    'plurid-route': HTMLPluridRouteElement
    'plurid-router': HTMLPluridRouterElement
    'plurid-routes': HTMLPluridRoutesElement
  }

  interface ElementTagNameMap {
    'plurid-app': HTMLPluridAppElement;
    'plurid-branch': HTMLPluridBranchElement;
    'plurid-bridge': HTMLPluridBridgeElement;
    'plurid-container': HTMLPluridContainerElement;
    'plurid-content': HTMLPluridContentElement;
    'plurid-controls': HTMLPluridControlsElement;
    'plurid-document': HTMLPluridDocumentElement;
    'plurid-options': HTMLPluridOptionsElement;
    'plurid-page': HTMLPluridPageElement;
    'plurid-root': HTMLPluridRootElement;
    'plurid-roots': HTMLPluridRootsElement;
    'plurid-scion': HTMLPluridScionElement;
    'plurid-shadow': HTMLPluridShadowElement;
    'plurid-sheet': HTMLPluridSheetElement;
    'plurid-solid': HTMLPluridSolidElement;
    'plurid-space': HTMLPluridSpaceElement;
    'plurid-viewcube': HTMLPluridViewcubeElement;
    'plurid-button': HTMLPluridButtonElement;
    'plurid-link': HTMLPluridLinkElement;
    'plurid-route': HTMLPluridRouteElement;
    'plurid-router': HTMLPluridRouterElement;
    'plurid-routes': HTMLPluridRoutesElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
