// #region module
export const requiredDependencies = [
    '@plurid/generate-plurid-app',
    '@plurid/elementql',
    '@plurid/elementql-client-react',
    '@plurid/plurid-data',
    '@plurid/plurid-engine',
    '@plurid/plurid-functions',
    '@plurid/plurid-functions-react',
    '@plurid/plurid-icons-react',
    '@plurid/plurid-pubsub',
    '@plurid/plurid-react',
    '@plurid/plurid-themes',
    '@plurid/plurid-ui-components-react',
    '@plurid/plurid-ui-state-react',
    '@plurid/plurid-react-server',
    '@reduxjs/toolkit',
    'cross-fetch',
    'cors',
    'dotenv',
    'hammerjs',
    'react',
    'react-dom',
    'react-helmet-async',
    'react-redux',
    'styled-components',
];


export const requiredDevelopmentDependencies = [
    '@types/cors',
    '@rollup/plugin-commonjs',
    '@rollup/plugin-json',
    '@rollup/plugin-node-resolve',
    '@rollup/plugin-url',
    '@vitejs/plugin-react',
    'compression-webpack-plugin',
    'concurrently',
    'copy-webpack-plugin',
    'css-loader',
    'eslint',
    'file-loader',
    'jest',
    'nodemon',
    'open',
    'redux-devtools-extension',
    'rimraf',
    'rollup',
    'rollup-plugin-peer-deps-external',
    'rollup-plugin-sourcemaps',
    'rollup-plugin-postcss',
    'rollup-plugin-terser',
    'postcss',
    'source-map-loader',
    'style-loader',
    'terser-webpack-plugin',
    'vite',
    'vite-tsconfig-paths',
    'webpack',
    'webpack-bundle-analyzer',
    'webpack-cli',
    'webpack-merge',
    'webpack-node-externals',
];

export const requiredDevelopmentTypescriptDependencies = [
    '@types/express',
    '@types/jest',
    '@types/node',
    '@types/react',
    '@types/react-dom',
    '@types/react-redux',
    '@types/styled-components',
    '@types/styled-components',
    '@types/react-stripe-elements',
    '@typescript-eslint/eslint-plugin',
    '@typescript-eslint/parser',
    'rollup-plugin-typescript2',
    'tslib',
    'ts-loader',
    'ts-jest',
    'tsconfig-paths-webpack-plugin',
    'typescript',
    'typescript-plugin-styled-components',
];

export const requiredDevelopmentJavascriptDependencies = [
    '@babel/core',
    '@babel/preset-env',
    '@babel/preset-react',
    'babel-loader',
    '@rollup/plugin-babel',
];
// #endregion module
